apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness
  labels:
    name: web
    version: "1.0"
spec:
  containers:
  - name: nginx-readiness-c
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    readinessProbe:
        initialDelaySeconds: 1
        periodSeconds: 1
        httpGet:
          port: 80
          path: /abc.html
          
