apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-readiness-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-c
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
          hostPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: index-file
        readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 2
            httpGet:
              scheme: HTTP
              host: localhost
              port: 80
              path: /abc.html
      volumes:
        - name: index-file
          hostPath:
              path: /Users/chiku11/Documents/k8s/probes/html